### ISSUE TITLE
Apply Banzai to Microsoft dataflow examples

### ISSUE THREAD

**Issue by JimSEOW** [NDecision/Banzai#2]
HI Eswann, 

It will help others to understand Banzai design faster if you could take know dataflow examples and provide demo or samples, in addition to Unit test examples

For example, please try 
(a) https://msdn.microsoft.com/en-us/library/hh228605(v=vs.110).aspx
(b) https://msdn.microsoft.com/en-us/library/hh228604(v=vs.110).aspx

Thank you

**Comment by smartmeter** [comment]
Any updates?

**Comment by ghost** [comment]
I'd like some data flow example with Banzai as well. I find Banzai much simpler to use than data flow.

**Comment by eric-swann-q2** [comment]
This is a question that IMO is really hard to answer.  TPL is very flexible and can be used in a wide variety of ways. I prefer it for smaller contained tasking/paralellization.  I prefer Banzai for larger scale system workflow operations.  I created it initially for an enterprise ecommerce system where alternative logical workflows could be created and saved by the customer.  I use TPL when I have a bunch of data to stream to processors or process in a controlled parallel manner.  That's not to say you couldn't do with TPL what I do with Banzai.  I just thought it was somewhat difficult to understand when using it at that level.
